spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.202.247:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: myblog
    password: 123456

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

logging:
  level:
#    root: warn
#    com.pal: info
    root: info
    com.pal: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  file: log/blog-pro.log

server:
  port: 8080