spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

logging:
  level:
    root: warn
    com.pal: info
  file: log/blog-pro.log

server:
  port: 8081